server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Essa regra avisa o Nginx: "Se não achar o arquivo, redirecione para o index.html e deixe o Angular cuidar da rota"
    location / {
        try_files $uri $uri/ /index.html;
    }
}