/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/screentime/config/minor/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar configuração
         * @description Recupera os limites diários e a cotação de minutos por ficha de um menor específico.
         */
        get: operations["getConfig"];
        /**
         * Atualizar configuração
         * @description Define ou altera manualmente os limites de tempo de domingo a sábado e o valor de minutos por ficha.
         */
        put: operations["updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trocar senha
         * @description Reseta a senha e exclui o token
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar usuário
         * @description Registra um novo usuário Monitor
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout do sistema
         * @description Invalida o cookie de autenticação
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realiza login no sistema */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar reset
         * @description Solicita o reset para enviar um token no e-mail
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mudar senha
         * @description O usuário autenticado modifica a senha
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar usuário
         * @description Cria um novo usuário (monitor ou menor)
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/minor/{minorId}/deposit-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adicionar fichas
         * @description Monitor adiciona fichas à carteira do menor.
         */
        post: operations["depositTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/minor/{minorId}/deduct-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remover fichas
         * @description Monitor remove fichas da carteira do menor.
         */
        post: operations["deductToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/minor/{minorId}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Converter fichas
         * @description Converte uma quantidade informada de fichas do menor em dinheiro no cofre.
         */
        post: operations["convertTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar tarefa
         * @description Cria uma nova tarefa no sistema.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screentime/request/exchange-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trocar fichas por tempo de tela
         * @description Permite que o menor solicite a troca de fichas por minutos de tela. O sistema calcula o tempo automaticamente, e valida o limite do dia e o saldo de fichas.
         */
        post: operations["exchangeTokensForTime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minor-portal/piggy-bank/minor/{minorId}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar nova meta de economia
         * @description Cadastra uma meta ou item da wishlist para poupar dinheiro.
         */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minor-portal/piggy-bank/minor/{minorId}/goals/{goalId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resgatar dinheiro da meta
         * @description Devolve saldo da meta de volta para a carteira livre do menor.
         */
        post: operations["withdrawFromGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minor-portal/piggy-bank/minor/{minorId}/goals/{goalId}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guardar dinheiro na meta
         * @description Transfere saldo em dinheiro livre da carteira para uma meta de economia específica.
         */
        post: operations["depositToGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar família
         * @description Criação de uma nova família.
         */
        post: operations["createFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/minor/{minorId}/quotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar cotação
         * @description Define quanto vale cada ficha (Ex: 1 ficha = R$ 1.00)
         */
        patch: operations["updateQuotation"];
        trace?: never;
    };
    "/api/wallets/minor/{minorId}/interest-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Configurar Juros
         * @description Ativa/Desativa rendimento e define a taxa e frequência.
         */
        patch: operations["configInterest"];
        trace?: never;
    };
    "/api/tasks/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reprovar tarefa
         * @description Reprova uma tarefa concluída, enviando um motivo e permitindo que o menor a refaça.
         */
        patch: operations["rejectTask"];
        trace?: never;
    };
    "/api/tasks/{id}/conclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marcar concluída
         * @description Marca uma tarefa como concluída pelo menor
         */
        patch: operations["completeTask"];
        trace?: never;
    };
    "/api/tasks/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aprovar tarefa
         * @description Permite que um monitor aprove e efetue o pagamento de uma tarefa
         */
        patch: operations["approveTask"];
        trace?: never;
    };
    "/api/screentime/request/{requestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Recusar solicitação (Monitor)
         * @description Permite que um monitor recuse um pedido de tempo de tela. Nenhuma ficha é descontada.
         */
        patch: operations["rejectRequest"];
        trace?: never;
    };
    "/api/screentime/request/{requestId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aprovar solicitação (Monitor)
         * @description Permite que um monitor aprove um pedido pendente. Ao aprovar, as fichas são debitadas da carteira do menor.
         */
        patch: operations["approveRequest"];
        trace?: never;
    };
    "/api/wallets/minor/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Carteira
         * @description Retorna os saldos, a cotação atual da ficha e as configurações de rendimento.
         */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meu perfil
         * @description Retorna os dados do usuário autenticado no sistema
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/minor/{minorId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Histórico
         * @description Retorna o histórico financeiro do menor
         */
        get: operations["getMinorTransactionalHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/minor/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as tarefas
         * @description Lista todas as tarefas de um menor específico.
         */
        get: operations["listAllTasksForMinor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/minor/{minorId}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tarefas pendentes
         * @description Lista apenas as tarefas pendentes de um menor específico.
         */
        get: operations["listAllPendingTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/family/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as tarefas
         * @description Lista todas as tarefas paginadas para uma família específica.
         */
        get: operations["listAllTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/family/{familyId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tarefas para aprovação
         * @description Lista todas as tarefas que necessitam de aprovação para uma família específica.
         */
        get: operations["listForApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screentime/request/family/{familyId}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar solicitações pendentes (Monitor)
         * @description Retorna uma lista de solicitações pendentes para alimentar as notificações.
         */
        get: operations["getPendingRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screentime/request/email-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ação via E-mail
         * @description Processa aprovação ou rejeição vinda do clique no e-mail sem precisar logar.
         */
        get: operations["handleEmailAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minor-portal/piggy-bank/minor/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter dados gerais do cofrinho
         * @description Retorna visão consolidada de saldo livre, metas, rendimento e metas ativas.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minor-portal/dashboard/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter dados do Dashboard
         * @description Retorna os resumos agregados de Carteira, Tempo de Tela, Missões do dia e Gamificação para um menor específico.
         */
        get: operations["getDashboard_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gamification/minor/{minorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar XP e Nível do Menor
         * @description Retorna o nível atual, XP acumulado, meta para o próximo nível e porcentagem calculada.
         */
        get: operations["getMinorGamification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar minhas famílias
         * @description Retorna todas as famílias às quais o monitor pertence.
         */
        get: operations["getMyFamilies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/family/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar membros
         * @description Listar todos os membros de uma família.
         */
        get: operations["familyList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove um usuário
         * @description Remove um usuário da família
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove uma tarefa
         * @description Remove uma tarefa pelo id
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Objeto de transferência para as configurações de tempo de tela e limites semanais */
        ScreenTimeConfigDTO: {
            /**
             * Format: int32
             * @description Quantidade de minutos que cada ficha/token concede
             * @example 30
             */
            minutesPerToken?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos na segunda-feira
             * @example 120
             */
            mondayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos na terça-feira
             * @example 120
             */
            tuesdayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos na quarta-feira
             * @example 120
             */
            wednesdayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos na quinta-feira
             * @example 120
             */
            thursdayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos na sexta-feira
             * @example 120
             */
            fridayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos no sábado
             * @example 240
             */
            saturdayLimit?: number;
            /**
             * Format: int32
             * @description Limite máximo de minutos permitidos no domingo
             * @example 240
             */
            sundayLimit?: number;
        };
        /** @description Dados para efetivar a troca da senha utilizando o token de segurança */
        ResetPasswordDTO: {
            /**
             * @description Token único gerado pelo sistema e enviado no link do e-mail
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            token?: string;
            /**
             * @description A nova senha escolhida pelo usuário
             * @example Heroi@2026
             */
            newPassword?: string;
        };
        /** @description Dados para registro público de um novo Monitor */
        UserRegisterDTO: {
            /**
             * @description Nome completo do usuário
             * @example Peter Parker
             */
            name?: string;
            /**
             * @description E-mail de acesso (deve ser único)
             * @example peter.parker@example.com
             */
            email?: string;
            /**
             * @description Senha de acesso
             * @example Spider@2026
             */
            password?: string;
            /**
             * @description URL do avatar escolhido no front-end
             * @example https://api.dicebear.com/8.x/bottts/svg?seed=Lucas
             */
            profilePictureUrl?: string;
        };
        /** @description Dados detalhados do perfil do usuário */
        UserResponseDTO: {
            /**
             * Format: int64
             * @description ID único do usuário
             * @example 5
             */
            id?: number;
            /**
             * @description Nome completo do usuário
             * @example Peter Parker
             */
            name?: string;
            /**
             * @description E-mail cadastrado
             * @example peter.parker@example.com
             */
            email?: string;
            /**
             * @description Papel ou nível de acesso
             * @example MENOR
             * @enum {string}
             */
            role?: "MONITOR" | "MINOR";
            /**
             * Format: int64
             * @description ID da família vinculada
             * @example 1
             */
            familyId?: number;
            /**
             * @description Nome da família vinculada para facilitar exibição no front-end
             * @example Vingadores
             */
            familyName?: string;
            /**
             * @description URL da foto de perfil gerada dinamicamente
             * @example https://api.dicebear.com/8.x/bottts/svg?seed=Nome
             */
            profilePictureUrl?: string;
        };
        /** @description Objeto de requisição para autenticação de usuários */
        LoginRequestDTO: {
            /**
             * @description Endereço de e-mail cadastrado do usuário
             * @example heroidarotina@example.com
             */
            email: string;
            /**
             * @description Senha de acesso do usuário
             * @example Senha@123456
             */
            password: string;
        };
        /** @description Objeto de resposta contendo os dados de autenticação e perfil do usuário */
        LoginResponseDTO: {
            /**
             * @description Token JWT para autenticação nas rotas protegidas
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token?: string;
            /**
             * Format: int64
             * @description ID único do usuário no banco de dados
             * @example 1
             */
            id?: number;
            /**
             * @description Nome completo do usuário
             * @example Tony Stark
             */
            name?: string;
            /**
             * @description Nível de permissão do usuário no sistema
             * @example ADMIN
             * @enum {string}
             */
            role?: "MONITOR" | "MINOR";
        };
        /** @description Dados necessários para solicitar o envio do link de recuperação de senha */
        ForgotPasswordDTO: {
            /**
             * @description E-mail cadastrado do usuário que deseja recuperar o acesso
             * @example marido@email.com
             */
            email?: string;
        };
        /** @description Dados necessários para mudança de senha - Usuário autenticado */
        ChangePasswordDTO: {
            /**
             * @description Antiga senha do usuário
             * @example senha@123
             */
            oldPassword?: string;
            /**
             * @description Nova senha do usuário
             * @example novaSenha@123
             */
            newPassword?: string;
        };
        /** @description Dados para cadastro de um novo usuário (Monitor ou Menor) */
        UserCreateDTO: {
            /**
             * @description Nome completo do usuário
             * @example Peter Parker
             */
            name?: string;
            /**
             * @description E-mail de acesso (deve ser único)
             * @example peter.parker@example.com
             */
            email?: string;
            /**
             * @description Senha de acesso
             * @example Spider@2026
             */
            password?: string;
            /**
             * @description Papel do usuário no sistema
             * @example MONITOR
             * @enum {string}
             */
            role?: "MONITOR" | "MINOR";
            /**
             * Format: int64
             * @description ID da família à qual o usuário será vinculado. Pode ser nulo se a família for criada posteriormente.
             * @example 1
             */
            familyId?: number | null;
            /**
             * @description URL do avatar escolhido no front-end
             * @example https://api.dicebear.com/8.x/bottts/svg?seed=Lucas
             */
            profilePictureUrl?: string;
        };
        DeductTokensRequestDTO: {
            /** Format: int32 */
            amount: number;
            motive: string;
        };
        ConvertTokensDTO: {
            /** Format: int32 */
            tokensToConvert: number;
        };
        /** @description Dados necessários para a criação de uma nova tarefa */
        TaskCreateDTO: {
            /**
             * @description Título curto da tarefa
             * @example Arrumar o quarto
             */
            title?: string;
            /**
             * @description Detalhamento do que deve ser feito
             * @example Organizar os brinquedos e dobrar as roupas
             */
            description?: string;
            /**
             * Format: int32
             * @description Quantidade de fichas/tokens que serão atribuídos como recompensa
             * @example 10
             */
            tokenReward?: number;
            /**
             * Format: int64
             * @description ID do usuário (menor/dependente) que deverá realizar a tarefa
             * @example 5
             */
            minorId?: number;
            /**
             * Format: int64
             * @description ID do monitor/responsável que está criando a tarefa
             * @example 2
             */
            monitorCreatorId?: number;
        };
        /** @description Dados de retorno detalhados de uma tarefa */
        TaskResponseDTO: {
            /**
             * Format: int64
             * @description Identificador único da tarefa
             * @example 101
             */
            id?: number;
            /**
             * @description Título da tarefa
             * @example Arrumar o quarto
             */
            title?: string;
            /**
             * @description Descrição detalhada da tarefa
             * @example Organizar os brinquedos e dobrar as roupas
             */
            description?: string;
            /**
             * Format: int32
             * @description Valor da recompensa em tokens ao concluir
             * @example 10
             */
            rewardTask?: number;
            /**
             * @description Status atual da tarefa (PENDENTE, CONCLUIDA, etc.)
             * @example PENDENTE
             * @enum {string}
             */
            status?: "PENDING" | "COMPLETED" | "APPROVED" | "REJECTED";
            /**
             * Format: int64
             * @description ID do executor da tarefa
             * @example 5
             */
            minorId?: number;
            /**
             * @description Nome do executor da tarefa
             * @example Miles Morales
             */
            minorName?: string;
            /**
             * Format: date-time
             * @description Data e hora de criação do registro
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description Data e hora em que a tarefa foi marcada como concluída
             */
            completedDate?: string;
            /**
             * Format: date-time
             * @description Data e hora em que a tarefa foi marcada como aprovada
             */
            approvalDate?: string;
            /**
             * @description Motivo da reprovação, caso a tarefa tenha sido rejeitada pelo monitor
             * @example Faltou varrer embaixo da cama.
             */
            rejectionReason?: string;
        };
        TokenExchangeRequestDTO: {
            /** Format: int64 */
            minorId: number;
            /** Format: int32 */
            tokens: number;
        };
        ScreenTimeResponseDTO: {
            /** Format: int64 */
            requestId?: number;
            /**
             * Format: int64
             * @description Id de quem pediu o tempo de tela
             * @example 3
             */
            minorId?: number;
            /**
             * @description Nome de quem pediu o tempo de tela
             * @example Maria Silva
             */
            minorName?: string;
            status?: string;
            /**
             * Format: int32
             * @description Quantidade de minutos solicitados
             * @example 15
             */
            requestedMinutes?: number;
            /**
             * Format: int32
             * @description Quantidade de minutos restantes
             * @example 10
             */
            remainingBalance?: number;
        };
        SavingsGoalCreateDTO: {
            title: string;
            description?: string;
            targetAmount: number;
            /** Format: date */
            targetDate?: string;
            icon?: string;
        };
        SavingsGoalResponseDTO: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            targetAmount?: number;
            currentAmount?: number;
            /** Format: double */
            progressPercentage?: number;
            /** Format: date */
            targetDate?: string;
            icon?: string;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        };
        SavingsGoalWithdrawDTO: {
            amount: number;
        };
        SavingsGoalDepositDTO: {
            amount: number;
        };
        /** @description Dados para criação de um novo grupo familiar */
        FamilyCreateDTO: {
            /**
             * @description Nome do clã ou grupo familiar
             * @example Família Pimentel
             */
            familyName?: string;
            /**
             * @description URL da foto de perfil gerada dinamicamente
             * @example https://api.dicebear.com/8.x/bottts/svg?seed=Nome
             */
            profilePictureUrl?: string;
        };
        /** @description Dados de retorno da família, incluindo seus integrantes */
        FamilyResponseDTO: {
            /**
             * Format: int64
             * @description ID único da família
             * @example 1
             */
            id?: number;
            /**
             * @description Nome da família
             * @example Os Incríveis
             */
            familyName?: string;
            /** @description Lista de usuários que pertencem a esta família */
            members?: components["schemas"]["UserResponseDTO"][];
            /**
             * @description URL da foto de perfil gerada dinamicamente
             * @example https://api.dicebear.com/8.x/bottts/svg?seed=Nome
             */
            profilePictureUrl?: string;
        };
        /** @description Representa a configuração da cotação do token/ficha */
        InterestConfigDTO: {
            /**
             * Format: double
             * @description Taxa de juros aplicada
             */
            rate?: number;
            /** @description Ativa/Inativa a taxa de juros */
            enabled?: boolean;
            /**
             * @description Define a frequência da taxa aplicada
             * @example Diariamente, Semanalmente e Mensalmente
             * @enum {string}
             */
            frequency?: "DAILY" | "WEEKLY" | "MONTHLY";
        };
        /** @description Dados para reprovar uma tarefa e solicitar que seja refeita */
        TaskRejectDTO: {
            /**
             * @description Motivo pelo qual a tarefa foi reprovada
             * @example Você guardou os brinquedos, mas esqueceu de arrumar a cama.
             */
            reason?: string;
        };
        /** @description Resumo do saldo e informações da carteira do usuário */
        WalletResponseDTO: {
            /**
             * Format: int64
             * @description ID da carteira
             * @example 10
             */
            id?: number;
            /**
             * Format: int64
             * @description ID do usuário (menor de idade/dependente) dono da carteira
             * @example 5
             */
            minorId?: number;
            /**
             * @description Nome do usuário dono da carteira
             * @example Peter Parker
             */
            minorName?: string;
            /**
             * Format: int32
             * @description Saldo atual em fichas/tokens
             * @example 150
             */
            tokensBalance?: number;
            /**
             * Format: double
             * @description Saldo atual em moeda real (R$)
             * @example 75.5
             */
            moneyBalance?: number;
            /**
             * Format: double
             * @description Exibe a cotação atual do token
             */
            tokenQuotation?: number;
            /**
             * Format: double
             * @description Taxa de juros mensal
             * @example 0.05
             */
            interestRate?: number;
            /** @description Ativa/Desativa taxa de juros automática */
            interestEnabled?: boolean;
            /**
             * @description Frequência do rendimento (DAILY, WEEKLY, MONTHLY)
             * @example WEEKLY
             * @enum {string}
             */
            interestFrequency?: "DAILY" | "WEEKLY" | "MONTHLY";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModel: {
            content?: Record<string, never>[];
            page?: components["schemas"]["PageMetadata"];
        };
        PiggyBankDashboardDTO: {
            liquidWalletBalance?: number;
            totalSavedInGoals?: number;
            totalPiggyBalance?: number;
            interestEnabled?: boolean;
            /** Format: double */
            interestRate?: number;
            interestFrequency?: string;
            projectedYieldNextCycle?: number;
            yieldMotivationMessage?: string;
            goals?: components["schemas"]["SavingsGoalResponseDTO"][];
        };
        GamificationSummaryDTO: {
            /** Format: int32 */
            currentLevel?: number;
            /** Format: int32 */
            currentXp?: number;
            /** Format: int32 */
            targetXp?: number;
            /** Format: int32 */
            completedTasksToday?: number;
            /** Format: int32 */
            totalTasksToday?: number;
            motivationalMessage?: string;
        };
        MinorDashboardResponseDTO: {
            wallet?: components["schemas"]["WalletSummaryDTO"];
            screenTime?: components["schemas"]["ScreenTimeSummaryDTO"];
            todayTasks?: components["schemas"]["TaskSummaryDTO"][];
            gamification?: components["schemas"]["GamificationSummaryDTO"];
            dailyReminder?: string;
        };
        ScreenTimeSummaryDTO: {
            /** Format: int32 */
            dailyLimitMinutes?: number;
            /** Format: int32 */
            usedMinutesToday?: number;
            /** Format: int32 */
            remainingMinutesToday?: number;
            /** Format: int32 */
            tokenToMinutesRatio?: number;
        };
        TaskSummaryDTO: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: int32 */
            tokenReward?: number;
            status?: string;
        };
        WalletSummaryDTO: {
            /** Format: int32 */
            tokenBalances?: number;
            /** Format: double */
            moneyBalances?: number;
            /** Format: double */
            tokenQuotation?: number;
            interestEnabled?: boolean;
            /** Format: double */
            interestRate?: number;
            interestFrequency?: string;
        };
        GamificationResponseDTO: {
            /** Format: int64 */
            userId?: number;
            /** Format: int32 */
            currentLevel?: number;
            /** Format: int32 */
            currentXp?: number;
            /** Format: int32 */
            targetXp?: number;
            /** Format: double */
            progressPercentage?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenTimeConfigDTO"];
                };
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenTimeConfigDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenTimeConfigDTO"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDTO"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    depositTokens: {
        parameters: {
            query: {
                amount: number;
                motive: string;
            };
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deductToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeductTokensRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    convertTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertTokensDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
        };
    };
    exchangeTokensForTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenExchangeRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenTimeResponseDTO"];
                };
            };
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavingsGoalResponseDTO"];
                };
            };
        };
    };
    withdrawFromGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalWithdrawDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavingsGoalResponseDTO"];
                };
            };
        };
    };
    depositToGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
                goalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalDepositDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavingsGoalResponseDTO"];
                };
            };
        };
    };
    createFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyCreateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FamilyResponseDTO"];
                };
            };
        };
    };
    updateQuotation: {
        parameters: {
            query: {
                value: number;
            };
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    configInterest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestConfigDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRejectDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectRequest: {
        parameters: {
            query: {
                monitorId: number;
            };
            header?: never;
            path: {
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveRequest: {
        parameters: {
            query: {
                monitorId: number;
            };
            header?: never;
            path: {
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletResponseDTO"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    getMinorTransactionalHistory: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModel"];
                };
            };
        };
    };
    listAllTasksForMinor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
        };
    };
    listAllPendingTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
        };
    };
    listAllTasks: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                familyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModel"];
                };
            };
        };
    };
    listForApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
        };
    };
    getPendingRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenTimeResponseDTO"][];
                };
            };
        };
    };
    handleEmailAction: {
        parameters: {
            query: {
                token: string;
                action: string;
                monitorId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PiggyBankDashboardDTO"];
                };
            };
        };
    };
    getDashboard_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MinorDashboardResponseDTO"];
                };
            };
        };
    };
    getMinorGamification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GamificationResponseDTO"];
                };
            };
        };
    };
    getMyFamilies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FamilyResponseDTO"][];
                };
            };
        };
    };
    familyList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"][];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
